plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // REST Assured
    implementation 'io.rest-assured:rest-assured:5.5.1'

    // TestNG
    testImplementation 'org.testng:testng:7.11.0'

    // Gson
    implementation 'com.google.code.gson:gson:2.13.1'
//    implementation 'org.apache.logging.log4j:log4j-api:2.24.3'
//    implementation 'org.apache.logging.log4j:log4j-core:2.24.3'
}

test {
    useTestNG(){
        if (System.getProperty("tag") != null) {

            includeGroups System.getProperty("tag")
        }
    }

    testLogging {
        showStandardStreams = true
    }
}